
services:
  redis:
    image: redis:7-alpine
    container_name: nestorc-redis
    restart: unless-stopped
    ports:
      - "6300:6379"
    volumes:
      - redis_data:/data

  web:
    build:
      context: .
    env_file:
      - .env
    restart: unless-stopped
    container_name: nestorc-web
    volumes:
      - .:/app:cached
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "14000:14000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    command: gunicorn project.wsgi:application --bind 0.0.0.0:14000

  celery:
    build:
      context: .
    env_file:
      - .env
    restart: unless-stopped
    container_name: nestorc-celery
    volumes:
      - .:/app:cached
    depends_on:
      - redis
      - web
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    command: celery -A project worker --loglevel=info

volumes:
  redis_data:
  static_volume:
  media_volume:
